name: hello-world
on: push
jobs:
  my-job:
    runs-on: s390x
    steps:
      - uses: actions/checkout@v3
      - name: my-step
        run: echo "${ACTIONS_RUNTIME_URL}_apis/pipelines/workflows/${GITHUB_RUN_ID}/artifacts"

