name: hello-world
on:
  pull_request:

jobs:
  my-job:
    uses: ./.github/workflows/reusable.yml
    strategy:
      matrix:
        val: [true, false]
        val2: [true, false]
    with:
      bool_var: ${{ matrix.val }}
      string_var: ${{ toJSON(matrix.val2) }}